default['logwatch']['email'] = "root@localhost"
default['logwatch']['detail'] = "Low"
default['logwatch']['range'] = "yesterday"
default['logwatch']['output'] = "stdout"
default['logwatch']['format'] = "text"
